language: php

php:
  - 7.1
python:
  - 3.6

cache:
  directories:
    - vendor

services:
  - docker

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan jwt:generate
  - php artisan migrate

script:
  - ./vendor/bin/phpunit

after_success:
  - docker build -t $DOCKER_IMAGE:$(git rev-parse HEAD | cut -c 1-8) -f docker/Dockerfile .
  - docker login -u $REGISTERY_USERNAME -p $REGISTERY_PASSWORD
  - docker push $DOCKER_IMAGE:$(git rev-parse HEAD | cut -c 1-8)
  - pip install --upgrade pip --user
  - pip install -U fandogh_cli --upgrade --user
  - fandogh login --username $FAN_USR --password $FAN_PASS <<< "y"
  - fandogh service apply -f fandogh.yaml -p IMAGE_URL=$DOCKER_IMAGE -p TAG=$(git rev-parse HEAD | cut -c 1-8) -p SEC_NAME=$FANDOGH_CRED -p DEPLOY_URL=$DEPLOY_URL -p APP_NAME=${APP_NAME} -p APP_URL=${APP_URL} -p APP_KEY=${APP_KEY} -p JWT_SECRET=${JWT_SECRET} -p DB_DATABASE=${DEPLOY_DB_DATABASE} -p DB_USER=${DEPLOY_DB_USERNAME} -p DB_PASS=${DEPLOY_DB_PASSWORD} -p DB_HOST=${DEPLOY_DB_HOST} -p REDIS_HOST=${REDIS_HOST}

notifications:
  email: true
